pub mod string_rotation;
pub mod zero_matrix;
pub mod matrix_rotation;
pub mod encoding;
pub mod one_edit_away;
pub mod palindrome_permutation;
pub mod urification;
pub mod is_permutation;
pub mod unique_chars;